### ISSUE TITLE
Not installable on Firefox

### ISSUE THREAD

**Issue by AstraLuma** [blackle/Right-Click-Borescope#3]
Firefox 98 on Mac

![image](https://user-images.githubusercontent.com/401438/160900504-3b528f7c-c521-425d-8a87-ae8a4a2a4c1b.png)

**Comment by blackle** [comment]
can you try this link? https://addons.mozilla.org/en-US/firefox/addon/right-click-borescope/

I accidentally linked the android version

**Comment by AstraLuma** [comment]
Oh, it's supposed to be compatible with android?

**Comment by blackle** [comment]
no, idk what the deal is with the mozilla add-ons website
