### ISSUE TITLE
parse srcset

### ISSUE THREAD

**Issue by blackle** [blackle/Right-Click-Borescope#4]
many size options in srcset attribute sometimes. imdb has many images like this, where the borescope doesn't pick up on the largest possible image

**Comment by jleedev** [comment]
Accessing [`img.currentSrc`][1] should do this automatically.

[1]: https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-currentsrc

**Comment by blackle** [comment]
thanks! I would like to make all of the available srcs available, however
